variables:
  #此处对git的子模块进行递归更新
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_macos:
  stage: build
  script:
    - scons -j8
    - python ./scripts/update_res.py all
  tags:
    - macos_awtk_env

build_win:
  stage: build
  script:
    - call %APP_ENV%\startup_app.bat
    - scons -j8
    - python.exe ./scripts/update_res.py all
  tags:
    - win_awtk_env
    
build_ubuntu:
  stage: build
  script:
    - scons -j8
    - python ./scripts/update_res.py all
  tags:
    - ubuntu_awtk_env