variables:
  #此处对git的子模块进行递归更新
  GIT_SUBMODULE_STRATEGY: recursive

image:
  name: docker.zhaoqi.info/awtk/ubuntu:awtk

stages:
  - build

build_macos:
  stage: build
  script:
    - scons -j8
    - python ./scripts/update_res.py all
    - ./bin/runTest
  tags:
    - macos_awtk_env

build_win:
  stage: build
  script:
    - call %APP_ENV%\startup_app.bat
    - scons -j8
    - python.exe scripts\update_res.py all
    - .\bin\runTest.exe
  tags:
    - win_awtk_env
    
build_ubuntu:
  stage: build
  script:
    - scons -j8
    - python ./scripts/update_res.py all
    - ./bin/runTest
  tags:
    - ubuntu_awtk_env

build_docker:
  stage: build
  script:
    - ls
    - pwd
    - python -V
    - scons -j8
  tags:
    - docker
  artifacts:
    name: artifacts
    expire_in: 1 day
    paths:
     - awtk/bin
